import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import prettier from 'eslint-config-prettier';

/**
 * Money-safety rules.
 *
 * The requirement is that currency amounts never touch JavaScript's `number`.
 * Documenting that in a style guide is not enough — people forget under
 * deadline. These rules make the mistake fail `pnpm lint` instead.
 *
 * Applied to every package that computes money. `Money` (packages/core) wraps
 * decimal.js and exposes only its own arithmetic, so arithmetic operators in
 * these directories are almost always a bug.
 */
const MONEY_CRITICAL_PATHS = [
  'packages/core/src/profit/**/*.ts',
  'packages/core/src/pricing/**/*.ts',
];

export default tseslint.config(
  {
    ignores: [
      '**/node_modules/**',
      '**/dist/**',
      '**/.next/**',
      '**/coverage/**',
      'docs/research/**',
      // Generated by Next.js on every build; not ours to lint.
      '**/next-env.d.ts',
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    rules: {
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      '@typescript-eslint/consistent-type-imports': [
        'error',
        { prefer: 'type-imports', fixStyle: 'inline-type-imports' },
      ],
      // Silent failure is the enemy of a system that moves money.
      '@typescript-eslint/no-floating-promises': 'off', // needs type info; enabled in typecheck CI
      eqeqeq: ['error', 'always', { null: 'ignore' }],
      'no-console': ['warn', { allow: ['warn', 'error'] }],
    },
  },
  {
    files: MONEY_CRITICAL_PATHS,
    rules: {
      'no-restricted-syntax': [
        'error',
        {
          selector:
            "BinaryExpression[operator=/^[*\\/%]$/], BinaryExpression[operator='+'] > Identifier, BinaryExpression[operator='-'] > Identifier",
          message:
            'Raw arithmetic is banned in money-critical code. Use the Money type (packages/core/src/types/money.ts), which is backed by decimal.js.',
        },
        {
          selector: "CallExpression[callee.object.name='Math']",
          message:
            'Math.* is banned in money-critical code — it operates on IEEE-754 doubles. Use Money.round()/Money.max()/Money.min().',
        },
        {
          selector: "CallExpression[callee.name='parseFloat']",
          message: 'parseFloat is banned in money-critical code. Use Money.fromString().',
        },
      ],
    },
  },
  {
    files: ['**/*.test.ts', 'scripts/**/*.ts'],
    rules: {
      'no-console': 'off',
      '@typescript-eslint/no-explicit-any': 'off',
    },
  },
  prettier,
);
